apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
  labels:
    app: debug
spec:
  hostNetwork: true
  hostPID: true
  containers:
  - name: debug-pod
    image: samos123/docker-toolbox:latest
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
    volumeMounts:
      - name: dockersock
        mountPath: "/var/run/docker.sock"
    securityContext:
      allowPrivilegeEscalation: true
      privileged: true
      capabilities:
        add: ["NET_ADMIN"]
  volumes:
  - name: dockersock
    hostPath:
      path: /var/run/docker.sock
